### ISSUE TITLE
mining gui roadmap

### ISSUE THREAD

**Issue by blahah** [Blahah/mozilla_science_fellowship#35]
- [x] get sciencefair working
  - [x] fulltext downloading from eupmc
  - [x] lens reading
  - [x] download all hits
- [x] initial interface wireframes
- [ ] `getpapers-api` <- js interface to getpapers
- [ ] choose a name!
- [x] app draft <- take `sciencefair` and make new components and views for basic search and download
  - break out components into packages?
- [ ] choose initial set of extraction tools
- [ ] look at including thresher + journal-scrapers
